import {
  Activity,
  BookOpen,
  BrainCircuit,
  ClipboardCheck,
  Compass,
  GitBranch,
  GraduationCap,
  MessageCircleQuestion,
  Route,
  Sparkles,
  Target,
} from 'lucide-react';

export const PLATFORM_CAPABILITIES = [
  {
    key: 'multi-agent',
    index: '01',
    title: '多智能体协同',
    eyebrow: '六大智能体按需分工，让每项建议都有可追溯的依据',
    description: '学情诊断、学习规划、专家等六大智能体协同处理学习任务，按需分工，每项建议都关联证据、约束与审核结果，贯穿学习全流程完成诊断、答疑与学习支持。',
    shortDescription: '学情诊断、学习规划、专家等六大智能体协同处理学习任务，按需分工，每项建议都关联证据、约束与审核结果，贯穿学习全流程完成诊断、答疑与学习支持。',
    icon: BrainCircuit,
    tone: 'emerald',
    actionLabel: '进入智能助教',
    targetIntent: { page: 'assistant', params: { newConversation: true } },
    features: [
      { title: '任务规划', description: '理解学习目标与当前需求，拆解任务并安排清晰的执行路径。', icon: Compass },
      { title: '记忆管理', description: '读取会话、学习偏好和有效历史，为协同执行补充连续上下文。', icon: BrainCircuit },
      { title: '学情诊断', description: '分析知识掌握、练习表现与学习节奏，定位当前薄弱环节。', icon: Activity },
      { title: '知识库管理', description: '检索教材、题目、视频与可信证据，为生成内容提供依据。', icon: BookOpen },
      { title: '专家', description: '综合任务要求与检索结果，生成计划、讲解、题目或试卷。', icon: GraduationCap },
      { title: '审核裁判', description: '检查事实依据、内容质量与发布条件，保障最终结果可靠可用。', icon: ClipboardCheck },
    ],
    flow: ['任务规划与上下文准备', '诊断、检索与专家生成', '审核裁判复核后交付'],
    preview: [
      { label: '任务规划', detail: '理解需求并安排执行路径' },
      { label: '记忆管理', detail: '读取会话、偏好与有效历史' },
      { label: '学情诊断', detail: '判断掌握状态与学习节奏' },
      { label: '知识库管理', detail: '检索教材、题目、视频与证据' },
      { label: '专家', detail: '生成计划、讲解、题目或试卷' },
      { label: '审核裁判', detail: '检查事实、质量与发布条件' },
    ],
  },
  {
    key: 'learning-path',
    index: '02',
    title: '个性化学习路径',
    eyebrow: '贯通目标、计划与近期学情的安全进阶路线',
    description: '结合考试目标、阶段计划与近期答题表现，在前置知识、复习到期和可用时间等约束下，生成可解释、可调整的学习路径。',
    shortDescription: '结合考试目标、阶段计划与近期答题表现，在前置知识、复习到期和可用时间等约束下，生成可解释、可调整的学习路径。',
    icon: Route,
    tone: 'blue',
    actionLabel: '查看我的学习路径',
    targetIntent: { page: 'learning-path', params: {} },
    features: [
      { title: '目标拆解', description: '把资格考试目标拆分为阶段、主题与可执行的学习任务。', icon: Target },
      { title: '动态规划', description: '基于完成进度和掌握变化，自动优化后续学习顺序。', icon: GitBranch },
      { title: '任务衔接', description: '串联教材学习、知识复习和题目练习，形成完整闭环。', icon: GraduationCap },
    ],
    flow: ['选择考试目标', '生成阶段化路径', '随学习表现动态更新'],
    preview: [
      { label: '基础构建', detail: '建立核心概念框架' },
      { label: '专题进阶', detail: '突破重点与难点' },
      { label: '冲刺巩固', detail: '强化练习与复习' },
    ],
  },
  {
    key: 'knowledge-graph',
    index: '03',
    title: '专项练习',
    eyebrow: '把诊断结论转化为可完成的练习任务',
    description: '围绕薄弱点提供章节练习、错题变式、病例练习与试卷生成，把诊断结论转化为可完成的练习任务。',
    shortDescription: '围绕薄弱点提供章节练习、错题变式、病例练习与试卷生成，把诊断结论转化为可完成的练习任务。',
    icon: MessageCircleQuestion,
    tone: 'violet',
    actionLabel: '进入练习工坊',
    targetIntent: { page: 'practice', params: {} },
    features: [
      { title: '章节练习', description: '按知识点和练习目标组织练习，及时巩固重点内容。', icon: BookOpen },
      { title: '错题变式', description: '围绕错误原因生成针对性练习，避免在同类题上反复失分。', icon: Sparkles },
      { title: '病例模拟', description: '在接近考试场景的案例中练习辨证思路与作答表达。', icon: GraduationCap },
    ],
    flow: ['选择练习目标', '完成专项练习或模拟', '根据结果继续巩固'],
    preview: [
      { label: '章节练习', detail: '围绕重点知识逐项练习' },
      { label: '错题巩固', detail: '用变式练习修正薄弱点' },
      { label: '病例模拟', detail: '在案例中练习临床思路' },
    ],
  },
  {
    key: 'human-collaboration',
    index: '04',
    title: '人机协同',
    eyebrow: '让学生参与推荐依据、任务调整与效果反馈',
    description: '学生可确认目标与时间、调整难度或更换资源，并查看推荐依据；任务反馈与完成效果共同进入下一轮路径和资源匹配。',
    shortDescription: '学生可确认目标与时间、调整难度或更换资源，并查看推荐依据；任务反馈与完成效果共同进入下一轮路径和资源匹配。',
    icon: MessageCircleQuestion,
    tone: 'orange',
    actionLabel: '参与路径调整',
    targetIntent: { page: 'learning-path', params: {} },
    features: [
      { title: '共同设定目标', description: '学生确认备考目标、可用时间、学习基础与信心，让计划从真实需求出发。', icon: Target },
      { title: '主动调整任务', description: '学习中可接受、修改、降难、换资源或请求帮助，不必被动接受推荐。', icon: MessageCircleQuestion },
      { title: '反馈进入下一轮', description: '把难度、有效性和相关性反馈，与完成率和掌握变化共同用于后续匹配。', icon: GitBranch },
    ],
    flow: ['确认目标与学习约束', '查看依据并调整任务', '反馈结果更新路径与资源'],
    preview: [
      { label: '目标确认', detail: '明确时间、基础与学习重点' },
      { label: '任务调整', detail: '接受、修改、降难或换资源' },
      { label: '效果反馈', detail: '共同更新下一轮路径与匹配' },
    ],
  },
];

export function getPlatformCapability(key) {
  return PLATFORM_CAPABILITIES.find((capability) => capability.key === key)
    || PLATFORM_CAPABILITIES[0];
}
