import {
  Activity,
  BookOpen,
  BrainCircuit,
  ClipboardCheck,
  Compass,
  GitBranch,
  GraduationCap,
  Lightbulb,
  MessageCircleQuestion,
  Network,
  Route,
  Sparkles,
  Target,
  TrendingUp,
} from 'lucide-react';

export const PLATFORM_CAPABILITIES = [
  {
    key: 'multi-agent',
    index: '01',
    title: '多智能体协同',
    eyebrow: '六类智能体贯穿学习全流程的 AI 协作系统',
    description: '任务规划、记忆管理、学情诊断、知识库管理、专家与审核裁判六类智能体共享学习上下文，按需分工、协同执行，让每一次学习都有清晰路径、可靠依据和质量保障。',
    shortDescription: '六类智能体按需分工、协同执行，贯穿学习全流程。',
    icon: BrainCircuit,
    tone: 'emerald',
    actionLabel: '进入智能助教',
    targetIntent: { page: 'assistant', params: { newConversation: true } },
    features: [
      { title: '任务规划', description: '理解学习目标与当前需求，拆解任务并安排清晰的执行路径。', icon: Compass },
      { title: '记忆管理', description: '读取会话、学习偏好和有效历史，为协同执行补充连续上下文。', icon: BrainCircuit },
      { title: '学情诊断', description: '分析知识掌握、训练表现与学习节奏，定位当前薄弱环节。', icon: Activity },
      { title: '知识库管理', description: '检索教材、题目、视频与可信证据，为生成内容提供依据。', icon: BookOpen },
      { title: '专家', description: '综合任务要求与检索结果，生成计划、讲解、题目或试卷。', icon: GraduationCap },
      { title: '审核裁判', description: '检查事实依据、内容质量与发布条件，保障最终结果可靠可用。', icon: ClipboardCheck },
    ],
    flow: ['任务规划与上下文准备', '诊断、检索与专家生成', '审核裁判复核后交付'],
    preview: [
      { label: '任务规划', detail: '理解需求并安排执行路径' },
      { label: '记忆管理', detail: '读取会话、偏好与有效历史' },
      { label: '学情诊断', detail: '判断掌握状态与学习节奏' },
      { label: '知识库管理', detail: '检索教材、题目、视频与证据' },
      { label: '专家', detail: '生成计划、讲解、题目或试卷' },
      { label: '审核裁判', detail: '检查事实、质量与发布条件' },
    ],
  },
  {
    key: 'learning-path',
    index: '02',
    title: '个性化学习路径',
    eyebrow: '从目标到每日任务的动态进阶路线',
    description: '系统依据学习目标、知识基础和实时掌握度生成专属路径，并在学习过程中持续调整内容顺序与复习节奏。',
    shortDescription: '基于目标和学习基础，动态生成清晰、高效的进阶路径。',
    icon: Route,
    tone: 'blue',
    actionLabel: '查看我的学习路径',
    targetIntent: { page: 'learning-path', params: {} },
    features: [
      { title: '目标拆解', description: '把资格考试目标拆分为阶段、主题与可执行的学习任务。', icon: Target },
      { title: '动态规划', description: '基于完成进度和掌握变化，自动优化后续学习顺序。', icon: GitBranch },
      { title: '任务衔接', description: '串联教材学习、知识复习和题目训练，形成完整闭环。', icon: GraduationCap },
    ],
    flow: ['选择考试目标', '生成阶段化路径', '随学习表现动态更新'],
    preview: [
      { label: '基础构建', detail: '建立核心概念框架' },
      { label: '专题进阶', detail: '突破重点与难点' },
      { label: '冲刺巩固', detail: '强化训练与复习' },
    ],
  },
  {
    key: 'knowledge-graph',
    index: '03',
    title: '知识图谱驱动',
    eyebrow: '把分散知识连接成可探索的中医知识网络',
    description: '通过知识图谱呈现概念之间的层级、关联与依赖关系，帮助快速理解知识脉络，并从薄弱点直达相关学习内容。',
    shortDescription: '连接中医知识脉络，让重点、关联与薄弱环节一目了然。',
    icon: BookOpen,
    tone: 'violet',
    actionLabel: '探索知识图谱',
    targetIntent: { page: 'knowledge', params: { view: 'atlas' } },
    features: [
      { title: '脉络可视化', description: '按考试大纲、教材章节和知识层级组织核心内容。', icon: Network },
      { title: '关联发现', description: '展示概念之间的前置、相似与应用关系，促进融会贯通。', icon: Lightbulb },
      { title: '薄弱定位', description: '叠加个人掌握数据，直观发现需要优先补强的知识节点。', icon: Target },
    ],
    flow: ['定位知识主题', '展开关联与层级', '进入内容或配套训练'],
    preview: [
      { label: '知识主干', detail: '考试大纲与教材结构' },
      { label: '关联网络', detail: '概念关系与知识依赖' },
      { label: '掌握图层', detail: '个人强项与薄弱环节' },
    ],
  },
  {
    key: 'data-growth',
    index: '04',
    title: '数据驱动成长',
    eyebrow: '用真实学习数据持续优化下一步行动',
    description: '汇总学习时长、任务进度、知识掌握与训练表现，形成可解释的成长画像，让每一次策略调整都有数据依据。',
    shortDescription: '追踪学习表现与能力变化，持续优化下一步学习策略。',
    icon: Activity,
    tone: 'orange',
    actionLabel: '查看学情报告',
    targetIntent: { page: 'personalization', params: { view: 'reports' } },
    features: [
      { title: '学习画像', description: '聚合目标、偏好、进度与学习行为，呈现个人学习状态。', icon: Sparkles },
      { title: '能力趋势', description: '持续追踪知识掌握和训练表现，识别阶段性变化。', icon: TrendingUp },
      { title: '策略建议', description: '结合薄弱项与复习周期，推荐更适合的下一步学习行动。', icon: Target },
    ],
    flow: ['采集学习与训练数据', '分析能力变化趋势', '推荐下一步学习策略'],
    preview: [
      { label: '学习进度', detail: '任务完成与投入趋势' },
      { label: '能力雷达', detail: '多维知识掌握变化' },
      { label: '成长建议', detail: '可执行的提升方向' },
    ],
  },
];

export function getPlatformCapability(key) {
  return PLATFORM_CAPABILITIES.find((capability) => capability.key === key)
    || PLATFORM_CAPABILITIES[0];
}
