import {
  Activity,
  BookOpen,
  BrainCircuit,
  ClipboardCheck,
  Compass,
  GitBranch,
  GraduationCap,
  MessageCircleQuestion,
  Route,
  Sparkles,
  Target,
} from 'lucide-react';

export const PLATFORM_CAPABILITIES = [
  {
    key: 'multi-agent',
    index: '01',
    title: '多智能体协同',
    eyebrow: '六类智能体按需分工，让每一步备考都有针对性的支持',
    description: '学情诊断、知识库管理、专家等六类智能体按需分工、协同执行，贯穿学习全流程完成诊断、答疑与学习支持。',
    shortDescription: '学情诊断、知识库管理、专家等六类智能体按需分工、协同执行，贯穿学习全流程完成诊断、答疑与学习支持。',
    icon: BrainCircuit,
    tone: 'emerald',
    actionLabel: '进入智能助教',
    targetIntent: { page: 'assistant', params: { newConversation: true } },
    features: [
      { title: '任务规划', description: '理解学习目标与当前需求，拆解任务并安排清晰的执行路径。', icon: Compass },
      { title: '记忆管理', description: '读取会话、学习偏好和有效历史，为协同执行补充连续上下文。', icon: BrainCircuit },
      { title: '学情诊断', description: '分析知识掌握、训练表现与学习节奏，定位当前薄弱环节。', icon: Activity },
      { title: '知识库管理', description: '检索教材、题目、视频与可信证据，为生成内容提供依据。', icon: BookOpen },
      { title: '专家', description: '综合任务要求与检索结果，生成计划、讲解、题目或试卷。', icon: GraduationCap },
      { title: '审核裁判', description: '检查事实依据、内容质量与发布条件，保障最终结果可靠可用。', icon: ClipboardCheck },
    ],
    flow: ['任务规划与上下文准备', '诊断、检索与专家生成', '审核裁判复核后交付'],
    preview: [
      { label: '任务规划', detail: '理解需求并安排执行路径' },
      { label: '记忆管理', detail: '读取会话、偏好与有效历史' },
      { label: '学情诊断', detail: '判断掌握状态与学习节奏' },
      { label: '知识库管理', detail: '检索教材、题目、视频与证据' },
      { label: '专家', detail: '生成计划、讲解、题目或试卷' },
      { label: '审核裁判', detail: '检查事实、质量与发布条件' },
    ],
  },
  {
    key: 'learning-path',
    index: '02',
    title: '个性化学习路径',
    eyebrow: '从目标到每日任务的动态进阶路线',
    description: '系统依据学习目标、知识基础和实时掌握度生成专属路径，并在学习过程中持续调整内容顺序与复习节奏。',
    shortDescription: '基于目标和学习基础，动态生成清晰、高效的进阶路径。',
    icon: Route,
    tone: 'blue',
    actionLabel: '查看我的学习路径',
    targetIntent: { page: 'learning-path', params: {} },
    features: [
      { title: '目标拆解', description: '把资格考试目标拆分为阶段、主题与可执行的学习任务。', icon: Target },
      { title: '动态规划', description: '基于完成进度和掌握变化，自动优化后续学习顺序。', icon: GitBranch },
      { title: '任务衔接', description: '串联教材学习、知识复习和题目训练，形成完整闭环。', icon: GraduationCap },
    ],
    flow: ['选择考试目标', '生成阶段化路径', '随学习表现动态更新'],
    preview: [
      { label: '基础构建', detail: '建立核心概念框架' },
      { label: '专题进阶', detail: '突破重点与难点' },
      { label: '冲刺巩固', detail: '强化训练与复习' },
    ],
  },
  {
    key: 'knowledge-graph',
    index: '03',
    title: '专项训练与模拟',
    eyebrow: '把薄弱点转成有针对性的练习与考场模拟',
    description: '围绕章节重点和易错内容，提供题目训练、错题变式、病例模拟与试卷生成，让每一次练习都更贴近资格考试。',
    shortDescription: '覆盖章节练习、错题变式、病例训练和试卷生成，把薄弱点转成可执行的练习。',
    icon: MessageCircleQuestion,
    tone: 'violet',
    actionLabel: '进入训练工坊',
    targetIntent: { page: 'practice', params: {} },
    features: [
      { title: '章节训练', description: '按知识点和训练目标组织练习，及时巩固重点内容。', icon: BookOpen },
      { title: '错题变式', description: '围绕错误原因生成针对性练习，避免在同类题上反复失分。', icon: Sparkles },
      { title: '病例模拟', description: '在接近考试场景的案例中训练辨证思路与作答表达。', icon: GraduationCap },
    ],
    flow: ['选择训练目标', '完成专项练习或模拟', '根据结果继续巩固'],
    preview: [
      { label: '章节练习', detail: '围绕重点知识逐项训练' },
      { label: '错题巩固', detail: '用变式练习修正薄弱点' },
      { label: '病例模拟', detail: '在案例中训练临床思路' },
    ],
  },
  {
    key: 'data-growth',
    index: '04',
    title: '知识库与资料溯源',
    eyebrow: '让教材、题库和可信资料为每一次学习提供依据',
    description: '集中检索与管理中医药教材、题目、视频和参考资料，为答疑、练习和复习建议提供可追溯的学习依据。',
    shortDescription: '集中检索教材、题库与可信资料，为答疑、训练和复习提供可追溯的依据。',
    icon: BookOpen,
    tone: 'orange',
    actionLabel: '进入知识库',
    targetIntent: { page: 'knowledge', params: {} },
    features: [
      { title: '资料检索', description: '从教材、题库、视频等内容中快速找到与问题相关的学习资料。', icon: BookOpen },
      { title: '可信引用', description: '为回答和学习建议标注资料来源，便于核对与深入学习。', icon: ClipboardCheck },
      { title: '内容管理', description: '持续整理和补充备考资料，让常用知识随时可查、可用。', icon: Sparkles },
    ],
    flow: ['检索相关资料', '查看可信依据', '用于答疑、训练与复习'],
    preview: [
      { label: '教材资料', detail: '围绕考试大纲整理内容' },
      { label: '题目资源', detail: '支持训练与错题巩固' },
      { label: '参考依据', detail: '答疑与学习建议可追溯' },
    ],
  },
];

export function getPlatformCapability(key) {
  return PLATFORM_CAPABILITIES.find((capability) => capability.key === key)
    || PLATFORM_CAPABILITIES[0];
}
