#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import sys
from pathlib import Path
from typing import Iterable


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPOSITORY_ROOT / "backend"))

from competition_app.legacy_asset_compat import (  # noqa: E402
    knowledge_component_root,
    knowledge_video_root,
)


REQUIRED_COMPONENT_ITEMS = (
    "data/backend_delivery/01_question_bank/formatted_questions.json",
    "data/backend_delivery/04_knowledge_points/final_knowledge_points.json",
    "data/backend_delivery/08_exam_learning_path_2025",
)


def _existing_source(value: str | None, *, label: str) -> Path | None:
    if not value:
        return None
    path = Path(value).expanduser().resolve()
    if not path.exists():
        raise SystemExit(f"{label} does not exist: {path}")
    return path


def _verify_component(source: Path) -> None:
    missing = [
        str(source / item)
        for item in REQUIRED_COMPONENT_ITEMS
        if not (source / item).exists()
    ]
    if missing:
        raise SystemExit("knowledge component is incomplete:\n- " + "\n- ".join(missing))


def _verify_video(source: Path) -> None:
    if not (source / "full_batch_results").is_dir():
        raise SystemExit(
            "knowledge video asset is incomplete: "
            + str(source / "full_batch_results")
        )


def _install(source: Path, destination: Path, *, mode: str, apply: bool) -> None:
    print(f"{mode}: {source} -> {destination}")
    if not apply:
        return
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists() or destination.is_symlink():
        if destination.resolve() == source.resolve():
            return
        raise SystemExit(f"destination already exists: {destination}")
    if mode == "link":
        destination.symlink_to(source, target_is_directory=True)
    else:
        shutil.copytree(source, destination, copy_function=shutil.copy2)


def _write_manifest(
    asset_root: Path,
    release: str,
    installed: Iterable[tuple[str, Path]],
    *,
    apply: bool,
) -> Path:
    destination = asset_root / "manifests" / "asset-manifest.json"
    payload: dict[str, object] = {}
    if destination.is_file():
        try:
            existing = json.loads(destination.read_text(encoding="utf-8-sig"))
        except (OSError, json.JSONDecodeError) as exc:
            raise SystemExit(f"existing asset manifest is invalid: {destination}") from exc
        if not isinstance(existing, dict) or existing.get("schema_version") != "1.0":
            raise SystemExit(f"existing asset manifest uses an unsupported schema: {destination}")
        payload.update(existing)
    assets = payload.get("assets")
    if not isinstance(assets, dict):
        assets = {}
    else:
        assets = dict(assets)
    assets.update(
        {name: str(path.relative_to(asset_root).as_posix()) for name, path in installed}
    )
    payload.update(
        {
            "schema_version": "1.0",
            "release_id": release,
            "assets": assets,
            "migration": {
                "source_data_is_deleted": False,
                "note": "Generated by scripts/migrate_external_assets.py",
            },
        }
    )
    print(f"manifest: {destination}")
    if apply:
        destination.parent.mkdir(parents=True, exist_ok=True)
        temporary = destination.with_suffix(".json.tmp")
        temporary.write_text(
            json.dumps(payload, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
        os.replace(temporary, destination)
    else:
        print(json.dumps(payload, ensure_ascii=False, indent=2))
    return destination


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Install external assets into the versioned Shizhen layout. Dry-run by default."
    )
    parser.add_argument("--asset-root", required=True)
    parser.add_argument("--release", default="2026-07-18")
    parser.add_argument("--knowledge-component-source")
    parser.add_argument("--knowledge-video-source")
    # Compatibility-only option for old deployment commands. It never moves or
    # modifies the source tree; new commands should use the neutral paths above.
    parser.add_argument("--knowledge-source", help=argparse.SUPPRESS)
    parser.add_argument("--vector-source")
    parser.add_argument("--textbook-source")
    parser.add_argument("--atlas-chapter-source")
    parser.add_argument("--mode", choices=("link", "copy"), default="link")
    parser.add_argument("--apply", action="store_true")
    args = parser.parse_args()

    asset_root = Path(args.asset_root).expanduser().resolve()
    component = _existing_source(
        args.knowledge_component_source, label="knowledge component source"
    )
    video = _existing_source(
        args.knowledge_video_source, label="knowledge video source"
    )
    legacy_release = _existing_source(
        args.knowledge_source, label="legacy knowledge release source"
    )
    if legacy_release is not None:
        if component is not None or video is not None:
            raise SystemExit(
                "--knowledge-source cannot be combined with canonical knowledge sources"
            )
        component = knowledge_component_root(legacy_release)
        video = knowledge_video_root(legacy_release)
    vectors = _existing_source(args.vector_source, label="vector source")
    textbooks = _existing_source(args.textbook_source, label="textbook source")
    atlas_chapters = _existing_source(
        args.atlas_chapter_source, label="Atlas chapter source"
    )
    if not any((component, video, vectors, textbooks, atlas_chapters)):
        raise SystemExit("at least one source must be supplied")

    installed: list[tuple[str, Path]] = []
    knowledge_release = asset_root / "knowledge" / "releases" / args.release
    if component is not None:
        _verify_component(component)
        _install(
            component,
            knowledge_release / "component",
            mode=args.mode,
            apply=args.apply,
        )
    if video is not None:
        _verify_video(video)
        _install(
            video,
            knowledge_release / "video",
            mode=args.mode,
            apply=args.apply,
        )
    if component is not None or video is not None:
        installed.append(("knowledge_delivery", knowledge_release))
    if vectors is not None:
        target = asset_root / "vectors" / "public" / args.release
        _install(vectors, target, mode=args.mode, apply=args.apply)
        installed.extend(
            (("question_vector_store", target), ("knowledge_vector_store", target))
        )
    if textbooks is not None:
        target = asset_root / "textbooks" / "public"
        _install(textbooks, target, mode=args.mode, apply=args.apply)
        installed.append(("textbook_pdfs", target))
    if atlas_chapters is not None:
        target = (
            asset_root
            / "knowledge-atlas"
            / "chapters"
            / "releases"
            / "2026-07-22"
        )
        _install(atlas_chapters, target, mode=args.mode, apply=args.apply)
        installed.append(("knowledge_atlas_chapters", target))
    _write_manifest(asset_root, args.release, installed, apply=args.apply)
    print("applied" if args.apply else "dry-run only; add --apply after reviewing the plan")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
