CREATE TABLE IF NOT EXISTS evolution_feedback (
    feedback_id VARCHAR(128) PRIMARY KEY,
    source_type VARCHAR(32) NOT NULL,
    trust_level VARCHAR(16) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'pending',
    execution_id VARCHAR(128) NULL,
    conversation_id VARCHAR(128) NULL,
    message_id VARCHAR(128) NULL,
    learner_id VARCHAR(128) NULL,
    task_type VARCHAR(64) NOT NULL,
    target_agent VARCHAR(64) NULL,
    owner_step_id VARCHAR(128) NULL,
    issue_type VARCHAR(96) NOT NULL,
    severity VARCHAR(16) NOT NULL DEFAULT 'warning',
    field_path VARCHAR(512) NOT NULL DEFAULT '',
    constraint_category VARCHAR(96) NOT NULL DEFAULT 'general',
    summary TEXT NOT NULL,
    source_case_id VARCHAR(128) NULL,
    dedup_key VARCHAR(64) NOT NULL UNIQUE,
    reviewer_id VARCHAR(128) NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    reviewed_at TIMESTAMP(6) NULL,
    INDEX idx_evolution_feedback_status (status),
    INDEX idx_evolution_feedback_source (source_type),
    INDEX idx_evolution_feedback_case (source_case_id),
    INDEX idx_evolution_feedback_created (created_at)
);

CREATE TABLE IF NOT EXISTS evolution_signatures (
    signature_id VARCHAR(128) PRIMARY KEY,
    signature_key VARCHAR(64) NOT NULL UNIQUE,
    task_type VARCHAR(64) NOT NULL,
    owner_step_id VARCHAR(128) NOT NULL,
    target_agent VARCHAR(64) NOT NULL,
    issue_type VARCHAR(96) NOT NULL,
    field_path VARCHAR(512) NOT NULL DEFAULT '',
    constraint_category VARCHAR(96) NOT NULL DEFAULT 'general',
    case_count INT NOT NULL DEFAULT 0,
    execution_count INT NOT NULL DEFAULT 0,
    high_trust_count INT NOT NULL DEFAULT 0,
    source_case_ids JSON NOT NULL,
    source_execution_ids JSON NOT NULL,
    candidate_ready TINYINT(1) NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    last_seen_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_evolution_signatures_ready (candidate_ready),
    INDEX idx_evolution_signatures_target (target_agent, task_type)
);

CREATE TABLE IF NOT EXISTS evolution_rules (
    rule_id VARCHAR(128) NOT NULL,
    version INT NOT NULL,
    signature_id VARCHAR(128) NOT NULL,
    natural_language_analysis LONGTEXT NOT NULL,
    contract_json JSON NOT NULL,
    strategy_text TEXT NOT NULL,
    status VARCHAR(24) NOT NULL DEFAULT 'draft',
    replay_metrics JSON NOT NULL,
    approved_by VARCHAR(128) NULL,
    reviewer_domain VARCHAR(16) NULL,
    approval_note TEXT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (rule_id, version),
    INDEX idx_evolution_rules_status (status),
    INDEX idx_evolution_rules_signature (signature_id)
);

CREATE TABLE IF NOT EXISTS evolution_rule_runs (
    run_id VARCHAR(128) PRIMARY KEY,
    rule_id VARCHAR(128) NOT NULL,
    rule_version INT NOT NULL,
    run_type VARCHAR(32) NOT NULL,
    execution_id VARCHAR(128) NULL,
    target_agent VARCHAR(64) NULL,
    matched TINYINT(1) NOT NULL DEFAULT 0,
    first_audit_decision VARCHAR(32) NULL,
    final_audit_decision VARCHAR(32) NULL,
    repair_count INT NOT NULL DEFAULT 0,
    released TINYINT(1) NOT NULL DEFAULT 0,
    metrics JSON NOT NULL,
    input_digest VARCHAR(64) NOT NULL DEFAULT '',
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_evolution_runs_rule (rule_id, rule_version),
    INDEX idx_evolution_runs_execution (execution_id),
    INDEX idx_evolution_runs_created (created_at)
);
